services:
  db:
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
