name: Build and Run Go Program

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        nodes: ["ip1", "ip2"]

    steps:
      - name: Deploy to ${{ matrix.nodes }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh-keyscan $SERVER_2_HOST >> ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@${{ matrix.nodes }} "cd /docker-compose-flask-app && git pull && docker compose up -d --build"
