name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copies the code
        uses: actions/checkout@v4

      - name:
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Run the test
        run: docker compose up -d && docker compose exec -it web python test_app.py

  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Copying code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: afalobaid9/capstone-flask:latest
          cache-to: afalobaid9/capstone-flask:latest
          tags: |
            afalobaid9/capstone-flask:latest
            afalobaid9/capstone-flask:${{ github.sha }}
